on:
  push:
    paths:
      - 'bash/**'
      - '.github/workflows/shellcheck.yml'

  pull_request:
    paths:
      - 'bash/**'
      - '.github/workflows/shellcheck.yml'

jobs:
  bash:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        format: tty
        scandir: './bash'

  dash:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run ShellCheck to check against dash shells
      uses: ludeeus/action-shellcheck@master
      with:
        format: tty
        scandir: './bash'
      env:
        SHELLCHECK_OPTS: --shell dash
