on:
  pull_request:
    paths:
      - 'bash/**'
      - '.github/workflows/shell_format.yml'

jobs:
  shfmt:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: actions/checkout@v6
    - name: Run shfmt with reviewdog
      uses: reviewdog/action-shfmt@v1.0.4
      with:
        fail_on_error: true
        workdir: 'bash'
        shfmt_flags: '-i 4 -ci'


